# create the index
# the index name is hardcoded
PUT
:
load_test_index
:
{
    "settings" : {
        "number_of_shards" : 1,
        "number_of_replicas" : 0
    }
}

# index a document
PUT:load_test_index/test_type/1:{ "name" : "alex" }

# index a document
PUT:load_test_index/test_type/2:{ "name" : "alex2" }

# delete the 2nd document
DELETE:load_test_index/test_type/1:

# refresh the index
POST:load_test_index/_refresh:{}

# index a template
PUT:_template/template_1:
{
  "index_patterns": ["te*", "bar*"],
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "_doc": {
      "_source": {
        "enabled": false
      },
      "properties": {
        "host_name": {
          "type": "keyword"
        },
        "created_at": {
          "type": "date",
          "format": "EEE MMM dd HH:mm:ss Z yyyy"
        }
      }
    }
  }
}

# index a template
PUT:_template/template2:@resource(scripts/template/template2.json)

# index settings
PUT:index-1:@resource(scripts/indices/index1.json)